{
    "openapi": "3.0.0",
    "servers": [
        {
            "url": "https://www.googleapis.com/plusDomains/v1"
        }
    ],
    "info": {
        "contact": {
            "name": "Google",
            "url": "https://google.com"
        },
        "description": "Builds on top of the Google+ platform for Google Apps Domains.",
        "title": "Google+ Domains",
        "version": "v1",
        "x-apiClientRegistration": {
            "url": "https://console.developers.google.com"
        },
        "x-apisguru-categories": [
            "social"
        ],
        "x-logo": {
            "url": "https://api.apis.guru/v2/cache/logo/https_developers.google.com_+_images_branding_g+128.png"
        },
        "x-origin": [
            {
                "converter": {
                    "url": "https://github.com/lucybot/api-spec-converter",
                    "version": "2.7.31"
                },
                "format": "google",
                "url": "https://www.googleapis.com/discovery/v1/apis/plusDomains/v1/rest",
                "version": "v1"
            }
        ],
        "x-preferred": true,
        "x-providerName": "googleapis.com",
        "x-serviceName": "plusDomains"
    },
    "tags": [
        {
            "name": "activities"
        },
        {
            "name": "audiences"
        },
        {
            "name": "circles"
        },
        {
            "name": "comments"
        },
        {
            "name": "media"
        },
        {
            "name": "people"
        }
    ],
    "paths": {
        "/activities/{activityId}": {
            "get": {
                "description": "Get an activity.",
                "operationId": "plusDomains.activities.get",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.me"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.stream.read"
                        ]
                    }
                ],
                "tags": [
                    "activities"
                ]
            }
        },
        "/activities/{activityId}/comments": {
            "get": {
                "description": "List all of the comments for an activity.",
                "operationId": "plusDomains.comments.list",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.stream.read"
                        ]
                    }
                ],
                "tags": [
                    "comments"
                ]
            },
            "post": {
                "description": "Create a new comment in reply to an activity.",
                "operationId": "plusDomains.comments.insert",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.stream.write"
                        ]
                    }
                ],
                "tags": [
                    "comments"
                ]
            }
        },
        "/activities/{activityId}/people/{collection}": {
            "get": {
                "description": "List all of the people in the specified collection for a particular activity.",
                "operationId": "plusDomains.people.listByActivity",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.stream.read"
                        ]
                    }
                ],
                "tags": [
                    "people"
                ]
            }
        },
        "/circles/{circleId}": {
            "delete": {
                "description": "Delete a circle.",
                "operationId": "plusDomains.circles.remove",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.circles.write"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    }
                ],
                "tags": [
                    "circles"
                ]
            },
            "get": {
                "description": "Get a circle.",
                "operationId": "plusDomains.circles.get",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.circles.read"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    }
                ],
                "tags": [
                    "circles"
                ]
            },
            "patch": {
                "description": "Update a circle's description. This method supports patch semantics.",
                "operationId": "plusDomains.circles.patch",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.circles.write"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    }
                ],
                "tags": [
                    "circles"
                ]
            },
            "put": {
                "description": "Update a circle's description.",
                "operationId": "plusDomains.circles.update",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.circles.write"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    }
                ],
                "tags": [
                    "circles"
                ]
            }
        },
        "/circles/{circleId}/people": {
            "delete": {
                "description": "Remove a person from a circle.",
                "operationId": "plusDomains.circles.removePeople",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.circles.write"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    }
                ],
                "tags": [
                    "circles"
                ]
            },
            "get": {
                "description": "List all of the people who are members of a circle.",
                "operationId": "plusDomains.people.listByCircle",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.circles.read"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    }
                ],
                "tags": [
                    "people"
                ]
            },
            "put": {
                "description": "Add a person to a circle. Google+ limits certain circle operations, including the number of circle adds. Learn More.",
                "operationId": "plusDomains.circles.addPeople",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.circles.write"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    }
                ],
                "tags": [
                    "circles"
                ]
            }
        },
        "/comments/{commentId}": {
            "get": {
                "description": "Get a comment.",
                "operationId": "plusDomains.comments.get",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.stream.read"
                        ]
                    }
                ],
                "tags": [
                    "comments"
                ]
            }
        },
        "/people/{userId}": {
            "get": {
                "description": "Get a person's profile.",
                "operationId": "plusDomains.people.get",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.me"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.profiles.read"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/userinfo.email"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/userinfo.profile"
                        ]
                    }
                ],
                "tags": [
                    "people"
                ]
            }
        },
        "/people/{userId}/activities": {
            "post": {
                "description": "Create a new activity for the authenticated user.",
                "operationId": "plusDomains.activities.insert",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.me"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.stream.write"
                        ]
                    }
                ],
                "tags": [
                    "activities"
                ]
            }
        },
        "/people/{userId}/activities/{collection}": {
            "get": {
                "description": "List all of the activities in the specified collection for a particular user.",
                "operationId": "plusDomains.activities.list",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.me"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.stream.read"
                        ]
                    }
                ],
                "tags": [
                    "activities"
                ]
            }
        },
        "/people/{userId}/audiences": {
            "get": {
                "description": "List all of the audiences to which a user can share.",
                "operationId": "plusDomains.audiences.list",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.circles.read"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.me"
                        ]
                    }
                ],
                "tags": [
                    "audiences"
                ]
            }
        },
        "/people/{userId}/circles": {
            "get": {
                "description": "List all of the circles for a user.",
                "operationId": "plusDomains.circles.list",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.circles.read"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.me"
                        ]
                    }
                ],
                "tags": [
                    "circles"
                ]
            },
            "post": {
                "description": "Create a new circle for the authenticated user.",
                "operationId": "plusDomains.circles.insert",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.circles.write"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.me"
                        ]
                    }
                ],
                "tags": [
                    "circles"
                ]
            }
        },
        "/people/{userId}/media/{collection}": {
            "post": {
                "description": "Add a new media item to an album. The current upload size limitations are 36MB for a photo and 1GB for a video. Uploads do not count against quota if photos are less than 2048 pixels on their longest side or videos are less than 15 minutes in length.",
                "operationId": "plusDomains.media.insert",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.me"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.media.upload"
                        ]
                    }
                ],
                "tags": [
                    "media"
                ]
            }
        },
        "/people/{userId}/people/{collection}": {
            "get": {
                "description": "List all of the people in the specified collection.",
                "operationId": "plusDomains.people.list",
                "security": [
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.circles.read"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.login"
                        ]
                    },
                    {
                        "Oauth2": [
                            "https://www.googleapis.com/auth/plus.me"
                        ]
                    }
                ],
                "tags": [
                    "people"
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "Oauth2": {
                "description": "Oauth 2.0 authentication",
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://accounts.google.com/o/oauth2/auth",
                        "scopes": {
                            "https://www.googleapis.com/auth/plus.circles.read": "View your circles and the people and pages in them",
                            "https://www.googleapis.com/auth/plus.circles.write": "Manage your circles and add people and pages. People and pages you add to your circles will be notified. Others may see this information publicly. People you add to circles can use Hangouts with you.",
                            "https://www.googleapis.com/auth/plus.login": "View your basic profile info, including your age range and language",
                            "https://www.googleapis.com/auth/plus.me": "Know who you are on Google",
                            "https://www.googleapis.com/auth/plus.media.upload": "Send your photos and videos to Google+",
                            "https://www.googleapis.com/auth/plus.profiles.read": "View your own Google+ profile and profiles visible to you",
                            "https://www.googleapis.com/auth/plus.stream.read": "View your Google+ posts, comments, and stream",
                            "https://www.googleapis.com/auth/plus.stream.write": "Manage your Google+ posts, comments, and stream",
                            "https://www.googleapis.com/auth/userinfo.email": "View your email address",
                            "https://www.googleapis.com/auth/userinfo.profile": "See your personal info, including any personal info you've made publically available"
                        },
                        "tokenUrl": "https://www.googleapis.com/oauth2/v4/token"
                    }
                }
            }
        }
    }
}